# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 02:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imager_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='highlighted',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='api',
            name='owner',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='imager_api', to=settings.AUTH_USER_MODEL),
        ),
    ]
