# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('username', models.CharField(help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, verbose_name='username')),
                ('location', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField(choices=[('15', '18'), ('19', '25'), ('26', '+')], null=True)),
                ('camera_type', models.CharField(choices=[('Phillips', 'zoomandsuch'), ('yourface', 'nozoomforyou')], default='Phillips', max_length=3)),
                ('user_images', models.ImageField(default='nothing.jpg', upload_to='')),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
