# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='imagerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='imagerprofile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='imagerprofile',
            name='last_name',
        ),
    ]
