# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera_type',
            field=models.CharField(choices=[('Phillips', 'zoomandsuch'), ('yourface', 'nozoomforyou')], default='Phillips', max_length=150),
        ),
    ]
