# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170624_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='username',
        ),
    ]
