# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0003_remove_imagerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='age',
            field=models.IntegerField(choices=[('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28')], null=True),
        ),
    ]
