# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 23:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date_uploaded', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('published', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('shared', 'Shared')], default='public', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y-%m-%d')),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date_uploaded', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('published', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('shared', 'Shared')], default='public', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='photo',
            field=models.ManyToManyField(to='user_images.Photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
