# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddImage',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
