# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='upload',
        ),
        migrations.AddField(
            model_name='images',
            name='image_upload',
            field=models.ImageField(default='no.jpg', upload_to='images'),
        ),
    ]
