# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='uploaded_images',
            field=models.ManyToManyField(to='user_images.Photo'),
        ),
    ]
