# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 00:30
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/%Y-%m-%d'),
        ),
    ]
