# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 03:50
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0002_auto_20170623_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_upload',
            field=sorl.thumbnail.fields.ImageField(default='no.jpg', upload_to='images'),
        ),
    ]
