# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 02:50
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0003_auto_20170625_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='uploaded_images/%Y-%m-%d'),
        ),
    ]
