# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0003_auto_20170624_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='author',
        ),
        migrations.RemoveField(
            model_name='images',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
    ]
