# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0004_auto_20170624_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_upload',
            field=models.ImageField(default='no.jpg', upload_to='images'),
        ),
    ]
