# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0004_auto_20170625_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='uploaded_images/%Y-%m-%d'),
        ),
    ]
