# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:57
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0005_auto_20170624_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_upload',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='images'),
        ),
    ]
