# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:16
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_images', '0006_auto_20170624_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='user_images/images'),
        ),
    ]
